#!/usr/bin/env python3
"""
AEO Advisor - モニタリング結果からAI改善提案を生成
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path
import urllib.request

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
BASE_DIR = Path(__file__).parent.parent


def get_advice(data: dict) -> str:
    """モニタリング結果をAIに分析させ、改善提案を生成"""
    
    config = data.get("config", {})
    brand_stats = data.get("brand_stats", {})
    target_brands = config.get("target_brands", [])
    
    # サマリー作成
    summary_lines = []
    for brand, stats in brand_stats.items():
        rate = stats["mentioned"] / stats["total"] * 100 if stats["total"] > 0 else 0
        label = "自社" if brand in target_brands else "競合"
        summary_lines.append(f"- {brand} ({label}): 言及率 {rate:.0f}% ({stats['mentioned']}/{stats['total']})")
        
        for query, qs in stats.get("by_query", {}).items():
            qrate = qs["mentioned"] / qs["total"] * 100 if qs["total"] > 0 else 0
            summary_lines.append(f"  - 「{query[:30]}...」: {qrate:.0f}%")
    
    # AIの実際の回答から、推薦パターンを抽出
    response_samples = []
    for r in data.get("results", [])[:5]:
        response_samples.append(f"Q: {r['query']}\nA: {r['response'][:200]}")
    
    prompt = f"""あなたはAEO（AI検索最適化）の実務コンサルタントです。
飲食店や中小企業のオーナーが**明日から実行できる**レベルの具体的な改善提案を生成してください。

## 重要ルール
- 「SEO対策を強化」「構造化データ整備」など抽象的な表現は禁止
- 必ず「何を」「どこで」「どうやって」を具体的に書く
- ITに詳しくないオーナーでも実行できる手順にする

## クライアント情報
- 企業名: {config.get('client_name', 'N/A')}
- 業種: {config.get('industry', 'N/A')}
- 地域: {config.get('region', 'N/A')}

## モニタリング結果
{chr(10).join(summary_lines)}

## AIが実際に返した回答（抜粋）
{chr(10).join(response_samples[:3])}

## 以下の形式で出力してください：

### 診断結果
- **現状**: AI検索（ChatGPT/Gemini等）で自店が推薦されない直接的な原因（2行）
- **競合との差**: 推薦されている店とされていない店の具体的な違い

### 施策一覧（10個）

| # | 何をするか（具体的に） | 何が改善されるか | 効果(5) | 手軽さ(5) | スコア(/25) | 所要時間 |
|---|----------------------|----------------|---------|----------|------------|---------|

### 🎯 TOP 3 推奨施策

**施策1: [具体的な施策名]（スコア /25）**
📌 **解決する問題**: AI検索で〇〇が原因で推薦されていない
📝 **やること（ステップ）**:
  1. [明日できる具体的アクション — 例：「Googleビジネスプロフィールにログインして、営業時間を最新に更新する」]
  2. [次にやること]
  3. [その次]
⏰ **所要時間**: 〇時間（初回）/ 週〇分（継続）
📈 **期待効果**: [具体的に何がどう変わるか — 例：「"コマ劇場近く 居酒屋"でChatGPTに聞いた時に店名が出るようになる」]
💰 **コスト**: 無料 / 月額〇円

**施策2: ...**
**施策3: ...**

### AIが推薦している競合の特徴
推薦されている店が「なぜAIに選ばれるのか」を具体的に分析し、真似すべきポイントを3つ挙げてください。
例：「鳥貴族は食べログで★3.5以上・口コミ200件超・公式サイトにメニュー全品写真付きで掲載」など。

日本語で回答してください。"""

    url = "https://api.openai.com/v1/chat/completions"
    req_data = json.dumps({
        "model": "gpt-4o-mini",
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 2000,
        "temperature": 0.7
    }).encode()
    
    req = urllib.request.Request(url, data=req_data, headers={
        "Content-Type": "application/json",
        "Authorization": f"Bearer {OPENAI_API_KEY}"
    })
    
    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read())
            return result["choices"][0]["message"]["content"]
    except Exception as e:
        return f"ERROR: {e}"


def main():
    # Find latest raw data
    data_dir = BASE_DIR / "data"
    
    if len(sys.argv) >= 2:
        data_path = Path(sys.argv[1])
    else:
        raw_files = sorted(data_dir.glob("raw-*.json"), reverse=True)
        if not raw_files:
            print("Error: No raw data found. Run aeo_monitor.py first.")
            sys.exit(1)
        data_path = raw_files[0]
    
    print(f"📖 データ読み込み: {data_path.name}")
    with open(data_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    print("🤖 AI改善提案を生成中...")
    advice = get_advice(data)
    
    # Save
    date_str = datetime.now().strftime("%Y-%m-%d_%H%M")
    advice_path = BASE_DIR / "reports" / f"advice-{date_str}.md"
    
    full_report = f"""# AEO改善提案レポート
**生成日時:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
**クライアント:** {data['config'].get('client_name', 'N/A')}

---

{advice}

---
*Generated by AEO Monitor Advisor*
"""
    
    with open(advice_path, "w", encoding="utf-8") as f:
        f.write(full_report)
    
    print(f"\n📊 レポート保存: {advice_path}")
    print("\n" + "=" * 50)
    print(full_report)
    
    # Also update dashboard data with advice
    dash_path = data_dir / "dashboard-latest.json"
    if dash_path.exists():
        with open(dash_path, "r", encoding="utf-8") as f:
            dash_data = json.load(f)
        dash_data["advice"] = advice
        dash_data["advice_generated_at"] = datetime.now().isoformat()
        with open(dash_path, "w", encoding="utf-8") as f:
            json.dump(dash_data, f, ensure_ascii=False, indent=2)
        print("✅ ダッシュボードデータに提案を追加")


if __name__ == "__main__":
    main()
