#!/usr/bin/env python3
"""
AEO Advisor - モニタリング結果からAI改善提案を生成
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path
import urllib.request

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
BASE_DIR = Path(__file__).parent.parent


def get_advice(data: dict) -> str:
    """モニタリング結果をAIに分析させ、改善提案を生成"""
    
    config = data.get("config", {})
    brand_stats = data.get("brand_stats", {})
    target_brands = config.get("target_brands", [])
    
    # サマリー作成
    summary_lines = []
    for brand, stats in brand_stats.items():
        rate = stats["mentioned"] / stats["total"] * 100 if stats["total"] > 0 else 0
        label = "自社" if brand in target_brands else "競合"
        summary_lines.append(f"- {brand} ({label}): 言及率 {rate:.0f}% ({stats['mentioned']}/{stats['total']})")
        
        for query, qs in stats.get("by_query", {}).items():
            qrate = qs["mentioned"] / qs["total"] * 100 if qs["total"] > 0 else 0
            summary_lines.append(f"  - 「{query[:30]}...」: {qrate:.0f}%")
    
    # AIの実際の回答から、推薦パターンを抽出
    response_samples = []
    for r in data.get("results", [])[:5]:
        response_samples.append(f"Q: {r['query']}\nA: {r['response'][:200]}")
    
    prompt = f"""あなたはAEO（AI Engine Optimization）の専門コンサルタントです。
以下のモニタリング結果を分析し、クライアントへの具体的な改善提案を生成してください。

## クライアント情報
- 企業名: {config.get('client_name', 'N/A')}
- 業種: {config.get('industry', 'N/A')}
- 地域: {config.get('region', 'N/A')}

## モニタリング結果
{chr(10).join(summary_lines)}

## AIの回答サンプル
{chr(10).join(response_samples[:3])}

## 分析・提案を以下の形式で出力してください：

### 1. 現状分析（3行以内）
### 2. 緊急度の高い施策（即効性のあるもの、3つ）
### 3. 中長期施策（1-3ヶ月で効果が出るもの、3つ）
### 4. 競合分析（言及されている競合の特徴と対策）
### 5. 推奨アクションプラン（1週間のTO-DO）

各施策には「期待効果」「難易度」「コスト」を明記してください。
日本語で回答してください。"""

    url = "https://api.openai.com/v1/chat/completions"
    req_data = json.dumps({
        "model": "gpt-4o-mini",
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 2000,
        "temperature": 0.7
    }).encode()
    
    req = urllib.request.Request(url, data=req_data, headers={
        "Content-Type": "application/json",
        "Authorization": f"Bearer {OPENAI_API_KEY}"
    })
    
    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read())
            return result["choices"][0]["message"]["content"]
    except Exception as e:
        return f"ERROR: {e}"


def main():
    # Find latest raw data
    data_dir = BASE_DIR / "data"
    
    if len(sys.argv) >= 2:
        data_path = Path(sys.argv[1])
    else:
        raw_files = sorted(data_dir.glob("raw-*.json"), reverse=True)
        if not raw_files:
            print("Error: No raw data found. Run aeo_monitor.py first.")
            sys.exit(1)
        data_path = raw_files[0]
    
    print(f"📖 データ読み込み: {data_path.name}")
    with open(data_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    print("🤖 AI改善提案を生成中...")
    advice = get_advice(data)
    
    # Save
    date_str = datetime.now().strftime("%Y-%m-%d_%H%M")
    advice_path = BASE_DIR / "reports" / f"advice-{date_str}.md"
    
    full_report = f"""# AEO改善提案レポート
**生成日時:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
**クライアント:** {data['config'].get('client_name', 'N/A')}

---

{advice}

---
*Generated by AEO Monitor Advisor*
"""
    
    with open(advice_path, "w", encoding="utf-8") as f:
        f.write(full_report)
    
    print(f"\n📊 レポート保存: {advice_path}")
    print("\n" + "=" * 50)
    print(full_report)
    
    # Also update dashboard data with advice
    dash_path = data_dir / "dashboard-latest.json"
    if dash_path.exists():
        with open(dash_path, "r", encoding="utf-8") as f:
            dash_data = json.load(f)
        dash_data["advice"] = advice
        dash_data["advice_generated_at"] = datetime.now().isoformat()
        with open(dash_path, "w", encoding="utf-8") as f:
            json.dump(dash_data, f, ensure_ascii=False, indent=2)
        print("✅ ダッシュボードデータに提案を追加")


if __name__ == "__main__":
    main()
